# Generated by Django 6.0.7 on 2026-09-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movies',
            name='release_year',
            field=models.IntegerField(default=2010),
            preserve_default=False,
        ),
    ]
